version: "3.8"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: db
    ports:
      - "5456:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Acgedb
    restart: unless-stopped
    networks:
      - acge_dev_network

  backend_django:
    build:
      context: ./acge_backend/
    restart: unless-stopped
    container_name: acgebackend
    environment:
      - SECRET_KEY="django-insecure-n=ofo^&1^z-w*jeio#zh&zj2je52y+zr4+)izlqt_b20cx!1q@"
      - DB_NAME=Acgedb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./acge_backend:/backend
    depends_on:
      - db
    networks:
      - acge_dev_network

  nginx:
    build:
      context: ./acge-web/
    restart: unless-stopped
    ports:
      - "8008:8008"
      - "4200:4200"

    volumes:
      - ./acge_backend/static:/static
      - ./nginx/:/etc/nginx/templates/
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8008
      - NGINX_URL=http://acgebackend:8000
      - WEB_PORT=4200
    networks:
      - acge_dev_network
    depends_on:
      - backend_django

networks:
  acge_dev_network:
    driver: bridge
