version: "3.8"

services:
  db:
    image: postgis/postgis:latest
    container_name: db
    ports:
      - "5456:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PORT= 5456
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Acgedb
    restart: unless-stopped
    networks:
      - acge_dev_network

  backend_django:
    build:
      context: ./acge_backend/
    restart: unless-stopped
    container_name: acge_backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY="django-insecure-n=ofo^&1^z-w*jeio#zh&zj2je52y+zr4+)izlqt_b20cx!1q@"
      - DB_NAME=Acgedb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./acge_backend:/backend
    depends_on:
      - db
    networks:
      - acge_dev_network

  nginx:
    build:
      context: ./acge-web/
    restart: unless-stopped
    ports:
      - "8008:8008"
      - "4200:4200"

    volumes:
      - ./statics:/acge_backend/statics
      - ./nginx/:/etc/nginx/templates/
    environment:
      - NGINX_HOST=8008
      - NGINX_PORT=localhost
      - NGINX_URL=http://acge_backend:8000
      - WEB_PORT=4200

    depends_on:
      - backend_django
networks:
  acge_dev_network:
    driver: bridge
